name: theme publish

on:
  push:
    branches:
      - dev
      
permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update overctrl.dbzer0.com
        run: |
          mkdir -p ~/.ssh/
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
          ssh -i ~/.ssh/private.key cduser@${WEBSERVER} 'cd div0-theme && git fetch && git checkout dev && git reset origin/dev --hard && git log -n 1'          
          ssh -i ~/.ssh/private.key cduser@${WEBSERVER} "cp div0-theme/random_cat_new.css ${EXTRA_THEMES_PATH}/"
          ssh -i ~/.ssh/private.key cduser@${WEBSERVER} "cp div0-theme/RandomLegend_dbzer0.css ${EXTRA_THEMES_PATH}/"
          ssh -i ~/.ssh/private.key cduser@${WEBSERVER} "cp div0-theme/background.webp ${EXTRA_THEMES_PATH}/"
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.CD_SSH_PRIVKEY}}
          SSH_KNOWN_HOSTS: ${{secrets.CD_KNOWN_HOSTS_DEV}}
          WEBSERVER: ${{secrets.CD_WEBSERVER_DEV_IP}}
          EXTRA_THEMES_PATH: "/lemmy/overctrl.dbzer0.com/volumes/lemmy-ui/extra_themes"
