name: theme publish

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update lemmy.dbzer0.com themes
        run: |
          mkdir -p ~/.ssh/
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
          ssh -i ~/.ssh/private.key cduser@${WEBSERVER} 'cd div0-theme && git fetch && git reset origin/main --hard && git log -n 1'          
          ssh -i ~/.ssh/private.key cduser@${WEBSERVER} "cp div0-theme/RandomLegend_dbzer0.css ${EXTRA_THEMES_PATH}/"
          ssh -i ~/.ssh/private.key cduser@${WEBSERVER} "cp div0-theme/Rblind_dark.css ${EXTRA_THEMES_PATH}/"
          ssh -i ~/.ssh/private.key cduser@${WEBSERVER} "cp div0-theme/Rblind_light.css ${EXTRA_THEMES_PATH}/"
          ssh -i ~/.ssh/private.key cduser@${WEBSERVER} "cp div0-theme/background.webp ${EXTRA_THEMES_PATH}/"
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.CD_SSH_PRIVKEY}}
          SSH_KNOWN_HOSTS: ${{secrets.CD_KNOWN_HOSTS}}
          WEBSERVER: ${{secrets.CD_WEBSERVER_IP}}
          EXTRA_THEMES_PATH: "/lemmy/lemmy.dbzer0.com/volumes/lemmy-ui/extra_themes"
